# Generated by Django 5.2.5 on 2025-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('birth', models.DateTimeField(auto_now_add=True, verbose_name='Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Feriado')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
    ]
