# Generated by Django 5.2.6 on 2025-09-12 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Cadastro')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('birth', models.DateField(verbose_name='Nascimento')),
            ],
            options={
                'verbose_name': 'Aniversário',
                'verbose_name_plural': 'Aniversários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Cadastro')),
                ('name', models.CharField(max_length=150, verbose_name='Feriado')),
                ('date', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['name'],
            },
        ),
    ]
