# Generated by Django 5.2.5 on 2025-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='birth',
            field=models.DateField(auto_now_add=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
