# Generated by Django 5.2.5 on 2025-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_birthday_birth_alter_holidays_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ['name'], 'verbose_name': 'Aniversario', 'verbose_name_plural': 'Aniversarios'},
        ),
        migrations.AlterModelOptions(
            name='holidays',
            options={'ordering': ['name'], 'verbose_name': 'Feriado', 'verbose_name_plural': 'Feriados'},
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birth',
            field=models.DateField(verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
