# Generated by Django 4.2.1 on 2023-05-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_curso_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='cor',
            new_name='cor_botao',
        ),
        migrations.AddField(
            model_name='curso',
            name='cor_texto',
            field=models.CharField(default=1, max_length=10, verbose_name='Cor'),
            preserve_default=False,
        ),
    ]
