version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/pmcs_uteis
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=core_django.settings
      - PYTHONUNBUFFERED=1

    command: python manage.py runserver 0.0.0.0:8000
