services:
  nginx-proxy:
    container_name: nginx-uteis
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./staticfiles:/var/www/staticfiles
      - ./media:/var/www/media
    networks:
      - uteis-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  django-app:
    container_name: django-uteis
    build: .
    restart: always
    volumes:
      - ./:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    networks:
      - uteis-network
    depends_on:
      - nginx-proxy
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn --config gunicorn_config.py core_django.wsgi:application
      "

networks:
  uteis-network:
    driver: bridge
    attachable: true
