version: '3'
services:
  web:
    # container_name: pmcs_uteis-web  # Nome personalizado para o contêiner do serviço web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
