# Generated by Django 5.2.6 on 2025-09-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cadastro')),
                ('name', models.CharField(max_length=200, verbose_name='Categoria')),
                ('button_color', models.CharField(default='#0B5ED7', max_length=10, verbose_name='Cor Botões')),
                ('text_color', models.CharField(default='#ffffff', max_length=10, verbose_name='Cor Textos')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cadastro')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'PDM'), (2, 'Licitação')], verbose_name='Categoria')),
                ('document', models.CharField(max_length=100, verbose_name='Documento')),
                ('description', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Licitação',
                'verbose_name_plural': 'Licitações',
                'ordering': ['document'],
            },
        ),
        migrations.CreateModel(
            name='LegislationButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cadastro')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Botão Legislação',
                'verbose_name_plural': 'Botão Legislação',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cadastro')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Botão',
                'verbose_name_plural': 'Botões',
                'ordering': ['title'],
            },
        ),
    ]
