# Generated by Django 5.2.6 on 2025-09-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='active',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='legislation',
            name='active',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='legislationbutton',
            name='active',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='Ativo'),
        ),
    ]
