# Generated by Django 5.2.6 on 2025-09-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_button_active_category_active_legislation_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='active',
        ),
    ]
