# Generated by Django 5.2.6 on 2025-09-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_remove_button_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislation',
            options={'ordering': ['document'], 'verbose_name': 'Licitação/PDM', 'verbose_name_plural': 'Licitações/PDM'},
        ),
    ]
