# Generated by Django 5.2.6 on 2025-09-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_alter_legislation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Botão - Categoria', 'verbose_name_plural': 'Botões - Categorias'},
        ),
        migrations.AlterModelOptions(
            name='legislationbutton',
            options={'ordering': ['title'], 'verbose_name': 'Legislação Botão ', 'verbose_name_plural': 'Legislação Botão'},
        ),
    ]
