# Generated by Django 5.2.6 on 2025-09-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cadastro')),
                ('name', models.CharField(max_length=200, verbose_name='Grupo')),
                ('number', models.CharField(max_length=5, verbose_name='Numero')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cadastro')),
                ('name', models.CharField(max_length=150, verbose_name='Local')),
                ('phone', models.CharField(max_length=20, verbose_name='Contato')),
                ('address', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('operation', models.CharField(max_length=250, verbose_name='Funcionamento')),
                ('maps', models.URLField(max_length=250, verbose_name='Maps')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cadastro')),
                ('person', models.CharField(max_length=200, verbose_name='Pessoa')),
                ('internal_number', models.CharField(max_length=20, verbose_name='Numero Interno')),
                ('external_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Externo')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutional.group', verbose_name='Grupo')),
            ],
        ),
    ]
