# Generated by Django 5.2.6 on 2025-09-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialaddress',
            options={'ordering': ['name'], 'verbose_name': 'Endereço Oficial', 'verbose_name_plural': 'Endereços Oficiais'},
        ),
        migrations.AlterField(
            model_name='officialaddress',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='officialaddress',
            name='maps',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Maps'),
        ),
        migrations.AlterField(
            model_name='officialaddress',
            name='operation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Funcionamento'),
        ),
        migrations.AlterField(
            model_name='officialaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato'),
        ),
    ]
