# Generated by Django 5.2.6 on 2025-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_alter_officialaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialaddress',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Local'),
        ),
    ]
