# Generated by Django 5.2.6 on 2025-09-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0003_alter_officialaddress_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['group', 'person'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
