# Generated by Django 5.2.6 on 2025-09-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0005_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Endereço - Categoria', 'verbose_name_plural': 'Endereços - Categorias'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Contato - Grupo', 'verbose_name_plural': 'Contatos - Grupos'},
        ),
        migrations.AlterModelOptions(
            name='officialaddress',
            options={'ordering': ['name'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AddField(
            model_name='officialaddress',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='institutional.category', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
