# Generated by Django 5.2.6 on 2025-09-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0006_alter_category_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.CharField(default=1, max_length=5, verbose_name='Numero Grupo'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='officialaddress',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['address', 'person'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='institutional.officialaddress', verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
