# Generated by Django 5.2.6 on 2025-09-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0007_alter_schedule_group_alter_officialaddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='external_number',
        ),
    ]
