# Generated by Django 5.2.6 on 2025-09-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0008_remove_schedule_external_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='internal_number',
        ),
        migrations.AddField(
            model_name='schedule',
            name='person_num',
            field=models.CharField(default=1, max_length=10, verbose_name='Pessoa Numero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='sector',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sector_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Setor Numero'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutional.officialaddress', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='person',
            field=models.CharField(max_length=150, unique=True, verbose_name='Pessoa'),
        ),
    ]
