# Generated by Django 5.2.6 on 2025-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0009_remove_schedule_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado'),
        ),
        migrations.AlterField(
            model_name='officialaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastro'),
        ),
    ]
