# Generated by Django 4.2.1 on 2023-10-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('grupo', models.CharField(max_length=200, verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('pessoa', models.CharField(max_length=200, verbose_name='Pessoa')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.grupo', verbose_name='Agenda')),
            ],
        ),
    ]
