# Generated by Django 4.2.1 on 2023-10-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agenda_numero_agenda_numero_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.grupo', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='numero_externo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Externo'),
        ),
    ]
