# Generated by Django 4.2.1 on 2024-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_externa', '0002_alter_agenda_externa_ramal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda_externa',
            name='destino',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='agenda_externa',
            name='numero_externo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero:'),
        ),
        migrations.AlterField(
            model_name='agenda_externa',
            name='ramal',
            field=models.CharField(blank=True, max_length=4, verbose_name='Ramal (Se houver)'),
        ),
    ]
