# Generated by Django 4.2.1 on 2024-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_externa', '0003_alter_agenda_externa_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda_externa',
            name='numero_externo',
            field=models.CharField(default=1, max_length=20, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda_externa',
            name='ramal',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ramal (Se houver)'),
        ),
    ]
