# Generated by Django 4.2.1 on 2024-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_externa', '0004_alter_agenda_externa_numero_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda_externa',
            name='destino',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome'),
        ),
    ]
