# Generated by Django 4.2.1 on 2023-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='numero',
            field=models.CharField(default=1, max_length=5, verbose_name='Numero'),
            preserve_default=False,
        ),
    ]
