# Generated by Django 4.2.1 on 2023-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_grupo_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='numero',
        ),
        migrations.AddField(
            model_name='agenda',
            name='numero_externo',
            field=models.CharField(default=1, max_length=20, verbose_name='Numero Externo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='numero_interno',
            field=models.CharField(default=1, max_length=20, verbose_name='Numero Interno'),
            preserve_default=False,
        ),
    ]
