# Generated by Django 4.2.1 on 2024-06-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_Externa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('ramal', models.CharField(max_length=20, verbose_name='Ramal')),
                ('numero_externo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Externo')),
            ],
        ),
    ]
