# Generated by Django 4.2.1 on 2023-05-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
    ]
