# Generated by Django 4.2.1 on 2023-05-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_video_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
