# Generated by Django 4.2.1 on 2023-05-29 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_videoexcel_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('curso', models.CharField(max_length=200, verbose_name='Nome do Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Vídeo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.curso', verbose_name='Curso')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoExcel',
        ),
    ]
