# Generated by Django 4.2.1 on 2023-05-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_curso_video_delete_videoexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cor',
            field=models.CharField(default=1, max_length=10, verbose_name='Cor'),
            preserve_default=False,
        ),
    ]
