# Generated by Django 4.2.1 on 2023-05-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_rename_cor_curso_cor_botao_curso_cor_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cor_botao',
            field=models.CharField(max_length=10, verbose_name='Cor Botões'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cor_texto',
            field=models.CharField(max_length=10, verbose_name='Cor Textos'),
        ),
    ]
