# Generated by Django 5.2.6 on 2025-09-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0011_curso_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['data', 'curso'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['data', 'title'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
